source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:makingspace/iOS-Specs.git'

platform :ios, '<%= deployment_target %>'

# Add Application pods here
  pod 'MBProgressHUD', '~>0.9'
  pod 'MSNetworking'
  pod 'Masonry'
  pod 'pop', '~>1.0'
  pod 'MSSPopMasonry'

target :unit_tests, :exclusive => true do
  link_with '<%= test_target_name %>'
  pod 'Specta'
  pod 'Expecta'
  pod 'KIF'
  pod 'OCMockito'
  pod 'Swizzlean'
  pod 'OHHTTPStubs'
end

<% if enable_settings && use_cocoapods %>
# Copy acknowledgements to the Settings.bundle

post_install do | installer |
  require 'fileutils'

  pods_acknowledgements_path = 'Pods/Target Support Files/Pods/Pods-Acknowledgements.plist'
  settings_bundle_path = Dir.glob("**/*Settings.bundle*").first

  if File.file?(pods_acknowledgements_path)
    puts 'Copying acknowledgements to Settings.bundle'
    FileUtils.cp_r(pods_acknowledgements_path, "#{settings_bundle_path}/Acknowledgements.plist", :remove_destination => true)
  end
end
<% end %>
